---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh
spec:
  replicas: 5
  selector:
    matchLabels:
      app: linux
  template:
    metadata:
      labels:
        app: linux
    spec:
      containers:
      - name: worker-1
        image: ssh-connection-bot:latest
        command:
        - python3
        - start.py
        - --SSHD_USERNAME
        - <sshd_username>
        - --SSHD_PASSWORD
        - <sshd_password>
        - --SSHD_SERVER
        - <sshd_server_ip>
        - --CONCURRENCY
        - '1'
        imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
